### ISSUE TITLE
Typo: staking success message is "Successfully Transfer"

### ISSUE THREAD

**Issue by nhynes** [oasisprotocol/oasis-wallet-ext#123]
_Successfully Transferred_ or _Transfer Successful_ are acceptable alternatives.

**Comment by nhynes** [comment]
Also, should debonding transactions that end up as "pending" really be called _successful transfer_ at all? Maybe adding more status messages would be appropriate.

**Comment by tjanez** [comment]
We discussed this internally and perhaps the easiest thing would be to use a general term such as "Transaction Succeeded"?
