### ISSUE TITLE
Connect to ledger popup is too narrow for Chrome's prompt

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-ext#149]
![image](https://user-images.githubusercontent.com/3758846/139705315-8c80643d-3a4c-4157-a8ed-ed1632ca8bd4.png)

**Comment by lvshaoping007** [comment]
This is the pop-up window that comes with the chrome browser ,  should we change this ?

**Comment by pro-wh** [comment]
I tried running through a similar process in metamask, and they take you over to a full tab to do the Ledger setup. We could maybe do that if we can't change how Chrome does the pop-up

**Comment by lvshaoping007** [comment]
I will take a look here
