### ISSUE TITLE
Spellcheck the code (e.g. with cSpell)

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-ext#15]
By adding ./cSpell.json
```json
{
  "version": "0.1",
  "flagWords": [
    "witch",
    "singer"
  ],
  "words": [
    "oasisprotocol",
    "bignumber",
    "bech",
    "extensionizer",
    "webusb",
    "ledgerhq",
    "grpc",
    "qrcode",
    "Identicon",
    "jazzicon",
    "reduxjs",
    "Nacl",
    "tweetnacl",
    "hdpath",
    "hdkey",
    "axios",
    "wechat",
    "passworder",

    "testmodal",
    "subres",
    "WINDOWID",
    "Progressbar",
    "backoff",

    "debonding",
    "debond",
    "unbounding",
    "unactive",
    "cointypes",
    "delegators"
  ]
}
```
and running
```sh
npx cspell "src/i18n/en.json" "src/**/*.js" "src/**/*.scss"
```

finds 288 typos (e.g. vaildatorNode, lable, UPDATA_ENTRY_WITCH_ROUTE)

**Comment by aefhm** [comment]
I'd prioritize some over others. [This](https://github.com/oasisprotocol/oasis-wallet-ext/blob/f912f132cc22bec5d70541ddf46b90d7d28c6c6d/src/background/service/APIService.js#L593) is more useful for future maintainers.

**Comment by lukaw3d** [comment]
Hm, this won't find filename typos. `tree src | npx cspell stdin` found `AccounItem.js` and `recevie_bg.png`

**Comment by lukaw3d** [comment]
`NET_WORK_CONFIG` should probably be `NETWORK_CONFIG`

**Comment by lvshaoping007** [comment]
"passworder",（cryoto-lib）
 "delegators"
These two are keywords, so they cannot be modified

**Comment by lvshaoping007** [comment]
and how to check `NET_WORK_CONFIG ` ,   I try `tree src | npx cspell stdin` but can not check any file
