### ISSUE TITLE
paratime support for mainnet

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-wallet-ext#159]
follows #156 

On mainnet there will be different paratime IDs for Cipher and Emerald. Let's add support for different networks (testnet/mainnet) to have different known runtime IDs and enter the mainnet ones (when available, if not yet).

**Comment by lvshaoping007** [comment]
we may need a type or something else to make a diff between cipher and emera . now there have no idea to deal different id and different action

**Comment by pro-wh** [comment]
we have since adjusted the config to have different paratime IDs between testnet and mainnet
