### ISSUE TITLE
deposits in tx history show as positive in consensus account

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-wallet-ext#162]
follows #156 

depositing into a paratime reduces the balance in the consensus account, so we should rather show it as a minus, right?

**Comment by lvshaoping007** [comment]
yes , but there does not have paratime tx-history . we show consense history

**Comment by pro-wh** [comment]
That sounds like it's not in conflict with the proposal :+1: We should continue to show consensus transaction history.

**Comment by pro-wh** [comment]
These no longer show an amount, so they're neither positive nor negative :+1:
