### ISSUE TITLE
Networking switching not working after switching from ParaTimes tab to Wallet tab

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-wallet-ext#180]
Here is a reproducer (sorry for the poor video quality):
![wallet-issue](https://user-images.githubusercontent.com/2518544/146242145-05465691-f1e4-45a2-af69-6bba01d25e54.gif)

**Comment by lukaw3d** [comment]
Related code: https://github.com/oasisprotocol/oasis-wallet-ext/commit/b3009dde569d14e3096b678c2ad0eead16d16bc1

**Comment by pro-wh** [comment]
is that in a branch somewhere?

**Comment by pro-wh** [comment]
oh it was in #168
