### ISSUE TITLE
Change From/To order for transaction preview pop ups

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-wallet-ext#194]
Now that this has been changed for history records in #187, it would be great to also change it for transaction preview pop ups.

Currently, they still show:
![Screenshot from 2021-12-18 00-06-01](https://user-images.githubusercontent.com/2518544/146621220-72a091f7-3390-4a85-bca8-85fcdea9ce9b.png)

**Comment by pro-wh** [comment]
oh nice find
