### ISSUE TITLE
Remove oasis adress from emerald imported wallet

### ISSUE THREAD

**Issue by MessiasMorten** [oasisprotocol/oasis-wallet-ext#214]
I have noticed that several community members have made the mistake of transfering their tokens using the consensus transfer method to the assigned oasis1 address of their imported emerald mainnet wallet. Unless this address serves a spesific purpose for the end-user, it should be removed to prevent any confusing. See attached image for context.

https://i.imgur.com/Lxfwpsk.png

**Comment by lukaw3d** [comment]
Thanks! This should be fixed in next release with https://github.com/oasisprotocol/oasis-wallet-ext/pull/206

**Comment by pro-wh** [comment]
additional info: a block explorer wouldn't know from a deposit transaction that the destination is an ethereum-compatible address, so all it can do is show the equivalent oasis address

example (some recent transaction, not mine): https://www.oasisscan.com/paratimes/transactions/4d12110f3451b478c4a1370876b72905c540f08f007e0b8d29ea91071c1e791d?runtime=000000000000000000000000000000000000000000000000e2eaa99fc008f87f

>   "from": "oasis1qr787dmvqsukcypsfnl3vaeh3n57n2gzfqea3hsm",
>  "to": "oasis1qr3mks5zxa88h76gk84336s3q9e2ssuxtc47al8d",

it was kind of nice to have this displayed in the wallet so you could compare with the explorer listing, but it is indeed error prone and we're removing the display
