### ISSUE TITLE
Warn if user tries to transfer tokens to validator

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-wallet-ext#217]
Something like "This is a validator wallet address. Transferring tokens to this address does not stake your funds with the validator. Are you sure you want to continue?"

Related: https://github.com/oasisprotocol/oasis-wallet-web/issues/567

**Comment by Trinkolin** [comment]
Son of a bitch

**Comment by Trinkolin** [comment]
It's a shame from your platform - you should refund people - you have tokens - it's a bug from your part.
