### ISSUE TITLE
兼容钱包地址导致的转账错误

### ISSUE THREAD

**Issue by smartmimi** [oasisprotocol/oasis-wallet-ext#219]
你好，英文不熟练，所以使用中文来描述问题
有一个用户，使用插件版钱包里的"兼容以太坊“导入的钱包，钱包里包含两个地址
1、0x开头的地址，此处简称A
2、oasis开头的地址，此处简称B
他在从交易所提币过程中，提到了B地址。但是此地址在兼容钱包内无法操作。
使用同样的助记词/私钥，在官方钱包oasis网络上生成钱包，地址为C。
B和C不一致。
所以请问，如何获取地址B的控制权限，以及此地址的用途（如果无用，是否应该隐藏来避免用户错误的转账）

**Comment by pro-wh** [comment]
we'll be hiding that address B in an upcoming release #206
