### ISSUE TITLE
ParaTimes fail to load on MacOS

### ISSUE THREAD

**Issue by seanockert** [oasisprotocol/oasis-wallet-ext#244]
On MacOS, I'm unable to load Emerald ParaTime in the Oasis browser extension wallet. 

Error: "No Runtime Found"
MacOS version: 11 (Big Sur)
Browser: Brave 1.34.81 Chromium: 97.0.4692.99

However, it loads fine on a Windows PC (running on the same Wifi network) and I am able to transfer from Emerald to the Consensus. 

Screenshot comparing the ParaTimes tab in MacOS and Windows:

![oasis-wallet-paratimes](https://user-images.githubusercontent.com/574163/152636993-3a812517-b1ed-4717-8bb3-77ca9e605e5e.png)

---

The browser console shows that the following resources fail to load:

https://grpc.oasis.dev/oasis-core.Registry/GetRuntimes
https://grpc.oasis.dev/oasis-core.Staking/Account
https://grpc.oasis.dev/oasis-core.Consensus/GetSignerNonce

![oasis-wallet-console-error](https://user-images.githubusercontent.com/574163/152637008-2b726017-fdda-4128-af76-928c4a973ef2.png)

Timeout issue? MacOS application firewall? This seems like a bug.

**Comment by pro-wh** [comment]
Yeah, that does look like a network issue. Try to find out what's going wrong with your DNS when it tries to resolve grpc.oasis.dev.

**Comment by seanockert** [comment]
Thanks, you're right @pro-wh. It's a DNS config issue: macOS blocking `.dev` domains. 

.dev TLDs are usually used for local development, so it may be safer to serve these public resources from a `.com` or `.net` domain?

This resolved my issue (if anyone else encounters it): https://superuser.com/a/1413487

**Comment by pro-wh** [comment]
Nice find! Thanks for looking into this.
