### ISSUE TITLE
getHDpath dead code?

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-wallet-ext#26]
https://github.com/oasisprotocol/oasis-wallet-ext/blob/f912f132cc22bec5d70541ddf46b90d7d28c6c6d/src/background/service/APIService.js#L196-L202

couldn't find any uses of this

blocks #1

**Comment by peterjgilbert** [comment]
Fixed by https://github.com/oasisprotocol/oasis-wallet-ext/commit/a737f9e6b0d0d49930a928bae0cb5ca81d1d231b
