### ISSUE TITLE
Default gas fee for paratime withdrawal insufficient for Emerald

### ISSUE THREAD

**Issue by peterjgilbert** [oasisprotocol/oasis-wallet-ext#260]
The minimum gas price in Emerald has been increased to from 10 to 100 nROSE. The default gas fee for paratime withdrawal transactions should to be updated to account for this:
https://github.com/oasisprotocol/oasis-wallet-ext/blob/ccaf2b841888cd7187c89ab0e812b635f62efe64/src/popup/pages/Send/index.js#L187-L189

**Comment by lukaw3d** [comment]
Maybe also https://github.com/oasisprotocol/oasis-wallet-ext/blob/542bb4b0f6fa6928027378681819e61bdee3a054/src/background/api/txHelper.js#L312
