### ISSUE TITLE
Histopia - Content Security Policy directive: "frame-ancestors 'self' white-list

### ISSUE THREAD

**Issue by SaberDoTcodeR** [oasisprotocol/oasis-wallet-ext#276]
Hi, We are building a GameFi project on Cipher para time called Histopia. We have already deployed our NFT and token contract on the Cipher test net. As we showed our demo to @nhynes , our domain(histopia.io and its subdomains) needs to be white-listed so that we can deploy the MVP version of Histopia on Cipher testnet and connect the website to oasis wallet. 
You can see a [trailer of Histopia on Cipher](https://youtu.be/rCbwMHAcac8?t=12), which only works on localhost.

**Comment by pro-wh** [comment]
Hi, we'd prefer not to allow non-secure origins to connect. Could you serve the component that connects to the wallet over HTTPS?

**Comment by SaberDoTcodeR** [comment]
@pro-wh Thanks for your help.
