### ISSUE TITLE
Uuid not necessarily universal unique id

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-wallet-ext#3]
https://github.com/oasisprotocol/oasis-wallet-ext/blob/f912f132cc22bec5d70541ddf46b90d7d28c6c6d/src/popup/component/Toast/ToastContainer.js#L55-L57

this is used in

https://github.com/oasisprotocol/oasis-wallet-ext/blob/f912f132cc22bec5d70541ddf46b90d7d28c6c6d/src/popup/component/Toast/ToastContainer.js#L22

and it's unclear whether an UUID is really needed and what could happen if the id field could have collisions -- whether it's sent to any servers (i'm guessing not), and what would happen if somebody w/ a separate connection to the same server(s) were to guess the uuid value.  `Date().getTime()` is in milliseconds, so guessing it might require a few trials, but should definitely be feasible.

a comment as to the implications would be nice.  or rename this if an actual UUID/GUID is not needed.  if one _is_ actually needed, then using a real RFC-4122 compliant UUID might be nice, since there are existing uuid solutions, e.g., https://www.npmjs.com/package/uuid, which could be used.

tagging #1 for possible security implications

**Comment by tjanez** [comment]
The UUID code was removed in #139.
