### ISSUE TITLE
What happens if user tries to import from ledger twice

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-ext#55]
I don't have ledger to try this, so here are only first two steps (have two ledger windows open):

![Peek 2021-08-17 06-58](https://user-images.githubusercontent.com/3758846/129666194-75c2764f-a934-4155-a4a7-c5526e5cb1d9.gif)

- Open import from ledger, but don't complete the flow
- Open another import from ledger
- (have two ledger windows open)
- Complete the flow to import from ledger
- It seems to me that listener would get triggered twice: https://github.com/oasisprotocol/oasis-wallet-ext/blob/f912f132cc22bec5d70541ddf46b90d7d28c6c6d/src/utils/ledger.js#L12-L24

**Comment by peterjgilbert** [comment]
I will investigate this one

**Comment by peterjgilbert** [comment]
The behavior that I observed in trying to reproduce this seems ok--it allows you to import each address only once.
