### ISSUE TITLE
Account icon is inaccurate

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-ext#57]
https://github.com/oasisprotocol/oasis-wallet-ext/blob/f912f132cc22bec5d70541ddf46b90d7d28c6c6d/src/popup/component/AccountIcon/index.js#L19-L34

- `.slice(7, 16) ` doesn't use the whole address
- incorrectly converts bech32 with `charCodeAt`
- `parseInt` does not have enough precision to handle the value

**Comment by lukaw3d** [comment]
Should icon be consistent with web wallet?

**Comment by pro-wh** [comment]
anyone have reference for what the web wallet does?

**Comment by lukaw3d** [comment]
Oh, nope, there's no account icons in web wallet :shrug:
