### ISSUE TITLE
toNonExponential returns wrong values

### ISSUE THREAD

**Issue by lukaw3d** [oasisprotocol/oasis-wallet-ext#63]
https://github.com/oasisprotocol/oasis-wallet-ext/blob/dabb8b41c105b86bf7e526916541e9db9dc98d0c/src/utils/utils.js#L23

```js
[toNonExponential('1e-2'), toNonExponential('1.0e-2'), toNonExponential('10e-2')]
> ["0.01", "0.10", "0.010"]
expected: ["0.01", "0.01", "0.1"]
```

Related https://github.com/oasisprotocol/oasis-wallet-ext/issues/23

**Comment by lukaw3d** [comment]
@lvshaoping007 fyi: this also affects 
- https://github.com/LeastAuthority/auro-wallet-browser-extension/blob/c46ad68638085ffaee4ea4d27230f09c28bb9b6f/src/utils/utils.js#L20
- and https://github.com/bitcat365/auro-wallet-browser-extension/blob/f82cdab04bf3ce566d012b9af1e19a78200dde62/src/utils/utils.js#L20

**Comment by pro-wh** [comment]
huh, didn't automatically close in #62 
good find, btw
